name:  Notificaci贸n: Consulta de Cliente

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Nombre del cliente consultado'
        required: true
        default: 'Cliente Buscado Demo'
      user_name:
        description: 'Usuario que realiz贸 la consulta'
        required: true
        default: 'Usuario del Sistema'

jobs:
  notify_team:
    runs-on: ubuntu-latest
    steps:
      - name:  Notificaci贸n al equipo sobre consulta
        run: |
          CLIENTE_CONSULTADO="${{ github.event.inputs.client_name }}"
          USUARIO_CONSULTA="${{ github.event.inputs.user_name }}"
          echo "=========================================================="
          echo " Registro de Actividad: Consulta de Cliente "
          echo "Cliente: $CLIENTE_CONSULTADO"
          echo "Usuario que Consult贸: $USUARIO_CONSULTA"
          echo "----------------------------------------------------------"
          echo "Miembros Notificados:"
          echo "- Ana Garc铆a (Dev): Supervisar actividad."
          echo "- Carlos Mart铆nez (QA): Monitorear accesos al sistema."
          echo "=========================================================="