name: ğŸ” NotificaciÃ³n:Consulta de Cliente

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Nombre del cliente consultado'
        required: true
      user_name:
        description: 'Nombre del usuario que realizÃ³ la consulta'
        required: true

jobs:
  notify_team:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¬ NotificaciÃ³n al equipo sobre consulta
        run: |
          echo "=========================================================="
          echo "ğŸ” ACCIÃ“N DE SEGUIMIENTO: Consulta de Cliente ğŸ”"
          echo "Cliente: ${{ github.event.inputs.client_name }}"
          echo "Consultado por: ${{ github.event.inputs.user_name }}"
          echo "----------------------------------------------------------"
          echo "Miembros Notificados:"
          echo "- Ana GarcÃ­a (Dev): Monitorear la carga de la base de datos."
          echo "- Carlos MartÃ­nez (QA): Validar la respuesta del sistema."
          echo "=========================================================="
