name:  Notificaci贸n:Creaci贸n de Nuevo Cliente

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Nombre del nuevo cliente'
        required: true

jobs:
  notify_team:
    runs-on: ubuntu-latest
    steps:
      - name:  Notificaci贸n al equipo sobre nuevo cliente
        run: |
          echo "=========================================================="
          echo " ACCIN REQUERIDA: Nuevo Cliente Creado "
          echo "Cliente: ${{ github.event.inputs.client_name }}"
          echo "----------------------------------------------------------"
          echo "Miembros Notificados:"
          echo "- Ana Garc铆a (Dev): Revisar alta y datos iniciales."
          echo "- Carlos Mart铆nez (QA): Verificar la generaci贸n del archivo."
          echo "=========================================================="
